version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI_BASE
  build:
    commands:
      - echo Build started on `date`
      # Rename app.py to lambda_function.py for consistency with our previous definition, or adjust the Dockerfile/Lambda Handler.
      - mv app.py lambda_function.py
      - docker build -t $ECR_REPO_NAME:$ECR_IMAGE_TAG .
      - docker tag $ECR_REPO_NAME:$ECR_IMAGE_TAG $ECR_FULL_URI
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $ECR_FULL_URI
      - echo Build finished successfully!
artifacts:
  files:
    - '**/*'
